name: yacreader-tsugu
base: core24
version: '9.14.2-1'
summary: Fill out later
description: |
  Fill out later

grade: stable
confinement: strict

lint:
  ignore:
    - classic 
    - library

apps:
  yacreader-tsugu:
    command: usr/bin/YACReader
    extensions: [gnome]
    environment: 
      GIO_EXTRA_MODULES: $SNAP/usr/lib/x86_64-linux-gnu/gio/modules
      LD_LIBRARY_PATH: >
        $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
        $SNAP/usr/lib/x86_64-linux-gnu/libunarr:
        $SNAP/usr/lib/x86_64-linux-gnu:
        $SNAP/usr/lib:
        $SNAP/lib/x86_64-linux-gnu:
        $SNAP/lib:
        $LD_LIBRARY_PATH
      XDG_DATA_HOME: "$SNAP_USER_COMMON"
      HOME: "$SNAP_USER_COMMON"  
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      QML2_IMPORT_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/qml
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - network
      - removable-media
      - unity7

parts:
  yacreader-tsugu:
    source: https://download.opensuse.org/repositories/home:/selmf/xUbuntu_24.04/amd64/yacreader_${SNAPCRAFT_PROJECT_VERSION}_amd64.deb
    plugin: dump
    source-type: deb
    stage-packages:
      - libc6
      - libgcc-s1
      - libgl1
      - libpoppler-qt5-1
      - libqt5core5a
      - libqt5gui5
      - libqt5multimedia5
      - libqt5network5
      - libqt5qml5
      - libqt5quick5
      - libqt5quickwidgets5
      - libqt5sql5
      - libqt5widgets5
      - libstdc++6
      - libunarr1
      - libproxy1v5
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtgraphicaleffects
      - qt5-image-formats-plugins
      - libqt5sql5-sqlite
      - qt5-qmltooling-plugins
      - libqt5multimedia5-plugins
      - qtwayland5
      - qt5-gtk-platformtheme
      - libqt5gui5-gles
      - qtbase5-dev-tools
